import { Octokit } from 'octokit'
import type { Issue } from './types'

export class GitHubClient {
  private octokit: Octokit
  private owner: string
  private repo: string

  constructor(token: string, repoFullName: string) {
    this.octokit = new Octokit({ auth: token })
    const [owner, repo] = repoFullName.split('/')
    this.owner = owner
    this.repo = repo
  }

  async getRepoTree(): Promise<{ path: string; sha: string; type: string }[]> {
    const { data } = await this.octokit.rest.git.getTree({
      owner: this.owner,
      repo: this.repo,
      tree_sha: 'HEAD',
      recursive: 'true',
    })
    return data.tree
      .filter(item => item.type === 'blob' && item.path && item.sha)
      .map(item => ({ path: item.path!, sha: item.sha!, type: item.type! }))
  }

  async getFileContent(path: string): Promise<string> {
    const { data } = await this.octokit.rest.repos.getContent({
      owner: this.owner,
      repo: this.repo,
      path,
    })
    if ('content' in data && data.content) {
      return Buffer.from(data.content, 'base64').toString('utf-8')
    }
    throw new Error(`Cannot read file: ${path}`)
  }

  async getMultipleFiles(paths: string[]): Promise<Record<string, string>> {
    const results: Record<string, string> = {}
    await Promise.all(
      paths.map(async (path) => {
        try {
          results[path] = await this.getFileContent(path)
        } catch {
          // skip files that can't be read
        }
      })
    )
    return results
  }

  async createBranchAndPR(
    issue: Issue,
    fileChanges: { path: string; content: string }[]
  ): Promise<string> {
    const baseBranch = await this.getDefaultBranch()
    const baseRef = await this.getBranchRef(baseBranch)
    const branchName = `flyvision/fix-${issue.id.slice(0, 8)}`

    await this.octokit.rest.git.createRef({
      owner: this.owner,
      repo: this.repo,
      ref: `refs/heads/${branchName}`,
      sha: baseRef,
    })

    for (const file of fileChanges) {
      let existingSha: string | undefined
      try {
        const { data } = await this.octokit.rest.repos.getContent({
          owner: this.owner,
          repo: this.repo,
          path: file.path,
          ref: branchName,
        })
        if ('sha' in data) existingSha = data.sha
      } catch {
        // new file
      }

      await this.octokit.rest.repos.createOrUpdateFileContents({
        owner: this.owner,
        repo: this.repo,
        path: file.path,
        message: `fix: ${issue.title}`,
        content: Buffer.from(file.content).toString('base64'),
        branch: branchName,
        ...(existingSha ? { sha: existingSha } : {}),
      })
    }

    const { data: pr } = await this.octokit.rest.pulls.create({
      owner: this.owner,
      repo: this.repo,
      title: `[FlyVision] Fix: ${issue.title}`,
      body: this.buildPRBody(issue),
      head: branchName,
      base: baseBranch,
    })

    return pr.html_url
  }

  private async getDefaultBranch(): Promise<string> {
    const { data } = await this.octokit.rest.repos.get({
      owner: this.owner,
      repo: this.repo,
    })
    return data.default_branch
  }

  private async getBranchRef(branch: string): Promise<string> {
    const { data } = await this.octokit.rest.git.getRef({
      owner: this.owner,
      repo: this.repo,
      ref: `heads/${branch}`,
    })
    return data.object.sha
  }

  private buildPRBody(issue: Issue): string {
    return `## Bug Detected by FlyVision AI

**Type:** ${issue.type} | **Severity:** ${issue.severity} | **Confidence:** ${Math.round(issue.confidence * 100)}%

### Description
${issue.description}

### Root Cause
${issue.root_cause}

### Reproduction Steps
${issue.reproduction_steps}

### Affected Component
\`${issue.affected_component}\`

---
*This PR was automatically generated by FlyVision after detecting this issue in a user session recording.*`
  }
}
